language: go
go: 1.9
sudo: true # give us 7.5GB and >2 bursted cores.
before_install:
    - export PULUMI_ROOT=/opt/pulumi
    # Travis only fetches 50 commits by default, and we want them all so we can do git describe --tags
    # - git fetch --unshallow
    # Dep for Go dependency management.
    - go get -v github.com/golang/dep/cmd/dep
    # Gometalinter for good Go linting/hygiene.
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
    # Node.js 6.10.2 for all JavaScript code (to match AWS Lambda).
    - nvm install v6.10.2
    # Install Yarn as per https://yarnpkg.com/lang/en/docs/install-ci/#travis-tab.
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
    - export PATH=$HOME/.yarn/bin:$PATH
    # Install the AWS CLI so that we can publish the resulting release (if applicable) at the end.
    - pip install --upgrade --user awscli
    # Install Kubectl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin
    # Install Minikube
    - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.0/minikube-linux-amd64 && chmod +x minikube 
    - sudo mv ./minikube /usr/local/bin/
    - sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib"
    - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install virtualbox-5.0 dkms 
    # Configure minikube to use docker daemon
    # - eval $(minikube docker-env)
    # - sudo curl -L https://github.com/zchee/docker-machine-driver-xhyve/releases/download/v0.3.1/docker-machine-driver-xhyve -o /usr/local/bin/docker-machine-driver-xhyve
    # - sudo chown root:wheel /usr/local/bin/docker-machine-driver-xhyve
    # - sudo chmod u+s /usr/local/bin/docker-machine-driver-xhyve
    # Start minikube cluster with Docker
    - minikube start
install:
    # Clone the Pulumi repo and use install-locked.sh to install Pulumi components based on our Gopkg.lock.
    - git clone git@github.com:pulumi/home ${GOPATH}/src/github.com/pulumi/home
    - ${GOPATH}/src/github.com/pulumi/home/scripts/install-locked.sh ${PULUMI_ROOT} pulumi
    # Now restore all dependencies, after cloning, to rebuild vendor appropriately.
    - make ensure
script:
    - make travis_${TRAVIS_EVENT_TYPE}
notifications:
   # webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
