language: go
go: 1.9
sudo: true # give us 7.5GB and >2 bursted cores.
before_install:
    - export PULUMI_ROOT=/opt/pulumi
    # Travis only fetches 50 commits by default, and we want them all so we can do git describe --tags
    # - git fetch --unshallow
    # Dep for Go dependency management.
    - go get -v github.com/golang/dep/cmd/dep
    # Gometalinter for good Go linting/hygiene.
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
    # Node.js 6.10.2 for all JavaScript code (to match AWS Lambda).
    - nvm install v6.10.2
    # Install Yarn as per https://yarnpkg.com/lang/en/docs/install-ci/#travis-tab.
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
    - export PATH=$HOME/.yarn/bin:$PATH
    # Install the AWS CLI so that we can publish the resulting release (if applicable) at the end.
    - pip install --upgrade --user awscli
    # Install Homebrew
    - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    # Install docker-machine-driver-xhyve
    - brew install docker-machine-driver-xhyve
    - chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    - chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    # Install Kubectl
    - brew install kubectl
    #install minikube
    - brew cask install minikube
    - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-darwin-amd64 && chmod +x minikube && mv minikube /usr/local/bin/
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    # Configure minikube to use docker daemon
    - eval $(minikube docker-env)
    
    # Start minikube cluster with Docker
    - minikube start --vm-driver=xhyve
install:
    # Clone the Pulumi repo and use install-locked.sh to install Pulumi components based on our Gopkg.lock.
    - git clone git@github.com:pulumi/home ${GOPATH}/src/github.com/pulumi/home
    - ${GOPATH}/src/github.com/pulumi/home/scripts/install-locked.sh ${PULUMI_ROOT} pulumi
    # Now restore all dependencies, after cloning, to rebuild vendor appropriately.
    - make ensure
script:
    - make travis_${TRAVIS_EVENT_TYPE}
notifications:
   # webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
