language: go
go: 1.9
sudo: true # give us 7.5GB and >2 bursted cores.
env:
    - CHANGE_MINIKUBE_NONE_USER=true
before_install:
    - export PULUMI_ROOT=/opt/pulumi
    # Travis only fetches 50 commits by default, and we want them all so we can do git describe --tags
    # - git fetch --unshallow
    # Dep for Go dependency management.
    - go get -v github.com/golang/dep/cmd/dep
    # Gometalinter for good Go linting/hygiene.
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
    # Node.js 6.10.2 for all JavaScript code (to match AWS Lambda).
    - nvm install v6.10.2
    # Install Yarn as per https://yarnpkg.com/lang/en/docs/install-ci/#travis-tab.
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
    - export PATH=$HOME/.yarn/bin:$PATH
    # Ensure that we can access Pulumi's private NPM org.
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
    # Install the AWS CLI so that we can publish the resulting release (if applicable) at the end.
    - pip install --upgrade --user awscli

    - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl
    - sudo chmod +x kubectl 
    - sudo mv kubectl /usr/local/bin/
    - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - sudo chmod +x minikube 
    - sudo mv minikube /usr/local/bin/
    - sudo minikube start --vm-driver=none --kubernetes-version=v1.7.0
    - minikube update-context
    # - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; \
    #  until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
install:
    # Clone the Pulumi repo and use install-locked.sh to install Pulumi components based on our Gopkg.lock.
    - git clone git@github.com:pulumi/home ${GOPATH}/src/github.com/pulumi/home
    - ${GOPATH}/src/github.com/pulumi/home/scripts/install-locked.sh ${PULUMI_ROOT} pulumi
    # Now restore all dependencies, after cloning, to rebuild vendor appropriately.
    - make ensure
script:
    - make travis_${TRAVIS_EVENT_TYPE}
notifications:
   # webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
